### ISSUE TITLE
Search Product

### ISSUE THREAD

**Issue by vincentdelitz** [vincentdelitz/festival-database-with-java#14]
1. JSP: inserting product name = fine
2. JSP: Displaying all the products with similar names 
(-> maybe we need to expand our database to demonstrate that)
- I think the displayed attributes do not exactly fit when following the activity diagram -> Attributes to be listed:
   •    Product name
   •    Product ID
   •    Product Price
   •    Link: “See location” (or maybe better “Find offering shops”)
- Delete “back”-link ( we included that with the link on “Festival”)

**Comment by demirdagemir** [comment]
@Hermionee I'm sorry I should have checked this issue before. 😄   I already created a PR and most of it is already done. But if you worked on it we can merge yours.

**Comment by demirdagemir** [comment]
Closed with #23
