### ISSUE TITLE
 JSP: Display all the shops that offer selected Products

### ISSUE THREAD

**Issue by vincentdelitz** [vincentdelitz/festival-database-with-java#15]
- Header: “Shops that offer the Product: <ProductName>”
- I think the displayed attributes do not exactly fit when following the activity diagram -> Attributes to be listed:
   •    ShopID
   •    AreaName
   •    AreaID (?)
   •    AreaTyp (?)
- Delete “back”-link ( we included that with the link on “Festival”)

**Comment by MilenaZurmuehl** [comment]
Most of it I've already done! We just have to maybe change the way of displaying the results into a list in case we have several shops that offer the certain product!

**Comment by demirdagemir** [comment]
Closed with #23
